package oracle

import (
	"strings"
	"testing"

	"github.com/mstgnz/sqlmapper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// realOracleDDL is the verbatim output of DBMS_METADATA.GET_DDL from an Oracle
// 23ai server: every identifier double quoted and schema qualified, the identity
// clause spelled out in full, ENABLE on each constraint, USING INDEX on the keys,
// "TIMESTAMP (6)" with a space, and a view header carrying FORCE EDITIONABLE and
// a column list. Nothing here is hand-tidied.
const realOracleDDL = `
  CREATE TABLE "APP"."CUSTOMERS"
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE,
	"FULL_NAME" VARCHAR2(4000),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"SCORE" NUMBER(10,2) DEFAULT 0,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_CUSTOMERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "APP"."INVOICES"
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE,
	"AMOUNT" NUMBER(12,2) NOT NULL ENABLE,
	"ISSUED_ON" DATE NOT NULL ENABLE,
	 CONSTRAINT "CHK_AMOUNT" CHECK (amount >= 0) ENABLE,
	 CONSTRAINT "PK_INVOICES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_INVOICES_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "APP"."CUSTOMERS" ("ID") ON DELETE CASCADE ENABLE
   ) ;


  CREATE INDEX "APP"."IDX_INVOICES_CUSTOMER" ON "APP"."INVOICES" ("CUSTOMER_ID")
  ;


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APP"."ACTIVE_CUSTOMERS" ("ID", "EMAIL") AS
  SELECT id, email FROM customers WHERE is_active = 1;
`

func parseRealOracle(t *testing.T) *sqlmapper.Schema {
	t.Helper()
	schema, err := NewOracle().Parse(realOracleDDL)
	require.NoError(t, err)
	return schema
}

func TestRealOracleDDL_Identifiers(t *testing.T) {
	schema := parseRealOracle(t)
	require.Len(t, schema.Tables, 2)

	// The quotes and the APP. qualifier both have to come off, and Oracle's
	// upper-case folding has to be undone: carrying CUSTOMERS forward breaks on
	// MySQL, where the view body copied from the same dump says customers.
	assert.Equal(t, "customers", schema.Tables[0].Name)
	assert.Equal(t, "app", schema.Tables[0].Schema)
	assert.Equal(t, "invoices", schema.Tables[1].Name)

	require.Len(t, schema.Views, 1)
	assert.Equal(t, "active_customers", schema.Views[0].Name,
		"the FORCE EDITIONABLE keywords and the column list must not hide the name")
	assert.Contains(t, schema.Views[0].Definition, "SELECT id, email",
		"the body follows the header on the next line and must not be glued to AS")
}

func TestRealOracleDDL_Columns(t *testing.T) {
	schema := parseRealOracle(t)
	customers := schema.Tables[0]
	require.Len(t, customers.Columns, 6)

	byName := map[string]sqlmapper.Column{}
	for _, c := range customers.Columns {
		byName[c.Name] = c
	}

	t.Run("identity becomes auto increment", func(t *testing.T) {
		id := byName["id"]
		assert.True(t, id.AutoIncrement)
		// The identity option list must not be read as the type or the default.
		assert.Empty(t, id.DefaultValue)
		assert.NotContains(t, id.DataType, "GENERATED")
	})

	t.Run("types fold onto the shared vocabulary", func(t *testing.T) {
		assert.Equal(t, "varchar", byName["email"].DataType)
		assert.Equal(t, 255, byName["email"].Length)
		assert.Equal(t, "decimal", byName["score"].DataType)
		assert.Equal(t, 10, byName["score"].Length)
		assert.Equal(t, 2, byName["score"].Scale)
		// NUMBER(1,0) is an integer flag, not a decimal.
		assert.Equal(t, "smallint", byName["is_active"].DataType)
		// "TIMESTAMP (6)" carries a space and a precision, not a length.
		assert.Equal(t, "timestamp", byName["created_at"].DataType)
		assert.Equal(t, 0, byName["created_at"].Length)
	})

	t.Run("nullability is read, not assumed", func(t *testing.T) {
		// NOT NULL ENABLE must still register as NOT NULL, and a column without
		// it must stay nullable. Defaulting the field to its zero value marked
		// every Oracle column NOT NULL.
		assert.False(t, byName["email"].IsNullable)
		assert.True(t, byName["full_name"].IsNullable)
		assert.True(t, byName["score"].IsNullable)
	})

	t.Run("time defaults are functions, not literals", func(t *testing.T) {
		assert.Equal(t, "CURRENT_TIMESTAMP", byName["created_at"].DefaultValue)
		assert.Equal(t, "1", byName["is_active"].DefaultValue)
	})
}

func TestRealOracleDDL_Constraints(t *testing.T) {
	schema := parseRealOracle(t)
	invoices := schema.Tables[1]

	byType := map[string]sqlmapper.Constraint{}
	for _, c := range invoices.Constraints {
		byType[c.Type] = c
	}

	require.Contains(t, byType, "FOREIGN KEY")
	fk := byType["FOREIGN KEY"]
	assert.Equal(t, "fk_invoices_customer", fk.Name)
	assert.Equal(t, []string{"customer_id"}, fk.Columns)
	assert.Equal(t, "customers", fk.RefTable, "the APP. qualifier does not resolve elsewhere")
	assert.Equal(t, "CASCADE", fk.DeleteRule)

	require.Contains(t, byType, "CHECK")
	assert.Equal(t, "amount >= 0", byType["CHECK"].CheckExpression)

	require.Contains(t, byType, "PRIMARY KEY")
	assert.Equal(t, []string{"id"}, byType["PRIMARY KEY"].Columns)

	// USING INDEX must not stop the index statement from being read.
	require.Len(t, invoices.Indexes, 1)
	assert.Equal(t, "idx_invoices_customer", invoices.Indexes[0].Name)
	assert.Equal(t, []string{"customer_id"}, invoices.Indexes[0].Columns)
}

func TestOracleResolveType(t *testing.T) {
	o := &Oracle{}

	tests := []struct {
		name string
		col  sqlmapper.Column
		want string
	}{
		{"varchar keeps its length", sqlmapper.Column{DataType: "varchar", Length: 255}, "VARCHAR2(255)"},
		{"text has no length", sqlmapper.Column{DataType: "text", Length: 100}, "CLOB"},
		{"boolean has no equivalent", sqlmapper.Column{DataType: "boolean"}, "NUMBER(1)"},
		{"bigint", sqlmapper.Column{DataType: "bigint"}, "NUMBER(19)"},
		{"int", sqlmapper.Column{DataType: "int"}, "NUMBER(10)"},
		{"decimal keeps precision", sqlmapper.Column{DataType: "decimal", Length: 12, Scale: 2}, "NUMBER(12,2)"},
		{"jsonb has no native type", sqlmapper.Column{DataType: "jsonb"}, "CLOB"},
		{"uuid becomes a fixed string", sqlmapper.Column{DataType: "uuid"}, "VARCHAR2(36)"},
		{"timestamptz", sqlmapper.Column{DataType: "timestamptz"}, "TIMESTAMP WITH TIME ZONE"},
		{"bytea", sqlmapper.Column{DataType: "bytea"}, "BLOB"},
		{"array has no equivalent", sqlmapper.Column{DataType: "text", IsArray: true}, "CLOB"},
		{"enum", sqlmapper.Column{DataType: "enum"}, "VARCHAR2(255)"},
		{"unknown passes through", sqlmapper.Column{DataType: "sdo_geometry"}, "SDO_GEOMETRY"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, o.resolveType(tt.col))
		})
	}
}

func TestOracleDefaultLiteral(t *testing.T) {
	o := &Oracle{}

	// Oracle has no boolean, so a boolean default has to become the number the
	// column is now declared as.
	assert.Equal(t, "1", o.defaultLiteral(sqlmapper.Column{DefaultValue: "true"}, "NUMBER(1)"))
	assert.Equal(t, "0", o.defaultLiteral(sqlmapper.Column{DefaultValue: "false"}, "NUMBER(1)"))
	assert.Equal(t, "SYSTIMESTAMP", o.defaultLiteral(sqlmapper.Column{DefaultValue: "CURRENT_TIMESTAMP"}, "TIMESTAMP"))
	assert.Equal(t, "42", o.defaultLiteral(sqlmapper.Column{DefaultValue: "42"}, "NUMBER(10)"))
	assert.Equal(t, "'draft'", o.defaultLiteral(sqlmapper.Column{DefaultValue: "draft"}, "VARCHAR2(20)"))
	assert.Equal(t, "'it''s'", o.defaultLiteral(sqlmapper.Column{DefaultValue: "it's"}, "VARCHAR2(20)"))
}

// TestGeneratedExpressionsAreTranslated checks the behaviour through the
// generator; the expression layer itself is tested in internal/expr.
func TestGeneratedExpressionsAreTranslated(t *testing.T) {
	o := &Oracle{}

	assert.Equal(t, "CHECK (amount >= 0)",
		o.generateConstraintSQL(sqlmapper.Constraint{Type: "CHECK", CheckExpression: "(amount >= (0)::numeric)"}))

	// Oracle has no boolean, so a bare column used as a condition has to be
	// written as a comparison or the statement will not parse.
	assert.Equal(t, "CHECK (is_active <> 0)",
		o.generateConstraintSQL(sqlmapper.Constraint{Type: "CHECK", CheckExpression: "is_active"}))
}

func TestOracleGenerateFromForeignSchema(t *testing.T) {
	// A schema that arrived from PostgreSQL: none of these types exist in Oracle.
	schema := &sqlmapper.Schema{
		Tables: []sqlmapper.Table{
			{
				Name: "invoices",
				Columns: []sqlmapper.Column{
					{Name: "id", DataType: "bigint", AutoIncrement: true, IsNullable: false},
					{Name: "customer_id", DataType: "bigint", IsNullable: false},
				},
				Constraints: []sqlmapper.Constraint{
					{Name: "invoices_pkey", Type: "PRIMARY KEY", Columns: []string{"id"}},
					{Name: "fk_c", Type: "FOREIGN KEY", Columns: []string{"customer_id"},
						RefTable: "customers", RefColumns: []string{"id"}, DeleteRule: "CASCADE"},
				},
			},
			{
				Name: "customers",
				Columns: []sqlmapper.Column{
					{Name: "id", DataType: "bigint", AutoIncrement: true, IsNullable: false},
					{Name: "is_active", DataType: "boolean", DefaultValue: "true", IsNullable: false},
					{Name: "meta", DataType: "jsonb", IsNullable: true},
					{Name: "tags", DataType: "text", IsArray: true, IsNullable: true},
				},
				Constraints: []sqlmapper.Constraint{
					{Name: "customers_pkey", Type: "PRIMARY KEY", Columns: []string{"id"}},
				},
			},
		},
	}

	out, err := NewOracle().Generate(schema)
	require.NoError(t, err)

	assert.Contains(t, out, "GENERATED BY DEFAULT AS IDENTITY")
	assert.Contains(t, out, "is_active NUMBER(1) DEFAULT 1 NOT NULL")
	assert.Contains(t, out, "meta CLOB")
	assert.Contains(t, out, "tags CLOB")
	assert.Contains(t, out, "CONSTRAINT fk_c FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE")

	// The parent must precede the child even though the source listed it second.
	assert.Less(t, strings.Index(out, "CREATE TABLE customers"), strings.Index(out, "CREATE TABLE invoices"))

	assert.NotContains(t, out, "boolean", "Oracle has no boolean type")
	assert.NotContains(t, out, "jsonb", "Oracle has no jsonb type")
}

func TestOracleGenerateDropsUnsupportedForeignKeyRule(t *testing.T) {
	// Oracle has no ON UPDATE action at all, and supports only CASCADE and
	// SET NULL on delete. Emitting anything else is a syntax error.
	schema := &sqlmapper.Schema{
		Tables: []sqlmapper.Table{
			{Name: "parent", Columns: []sqlmapper.Column{{Name: "id", DataType: "bigint"}}},
			{
				Name:    "child",
				Columns: []sqlmapper.Column{{Name: "parent_id", DataType: "bigint"}},
				Constraints: []sqlmapper.Constraint{
					{Name: "fk", Type: "FOREIGN KEY", Columns: []string{"parent_id"},
						RefTable: "parent", RefColumns: []string{"id"},
						DeleteRule: "RESTRICT", UpdateRule: "CASCADE"},
				},
			},
		},
	}

	out, err := NewOracle().Generate(schema)
	require.NoError(t, err)
	assert.NotContains(t, out, "ON UPDATE")
	assert.NotContains(t, out, "ON DELETE RESTRICT")
}

// realRoutineDDL is what DBMS_METADATA writes with its default transform
// parameters, taken from Oracle 23ai. Note EDITIONABLE, the quoted
// schema-qualified names, the unnamed primary key, and the storage clause
// hanging off USING INDEX.
const realRoutineDDL = `  CREATE TABLE "SRC"."USERS"
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"N" NUMBER,
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE OR REPLACE EDITIONABLE TRIGGER "SRC"."BUMP" BEFORE INSERT ON users FOR EACH ROW
BEGIN
  :NEW.n := NVL(:NEW.n, 0) + 2;
END;
/
ALTER TRIGGER "SRC"."BUMP" ENABLE;


  CREATE OR REPLACE EDITIONABLE FUNCTION "SRC"."ADD_ONE" (v IN NUMBER) RETURN NUMBER IS
BEGIN
  RETURN v + 1;
END;
/
`

// An unnamed table constraint and a USING INDEX with a storage clause are both
// what DBMS_METADATA writes by default. The storage words used to be read as
// part of the key, and the word PRIMARY as a column name.
func TestOracle_RealDDLAnonymousPrimaryKey(t *testing.T) {
	schema, err := NewOracle().Parse(realRoutineDDL)
	assert.NoError(t, err)

	assert.Len(t, schema.Tables, 1)
	table := schema.Tables[0]

	assert.Equal(t, []string{"id", "n"}, []string{table.Columns[0].Name, table.Columns[1].Name},
		"the storage clause is not a column")

	assert.Len(t, table.Constraints, 1)
	assert.Equal(t, "PRIMARY KEY", table.Constraints[0].Type)
	assert.Empty(t, table.Constraints[0].Name, "DBMS_METADATA wrote no name")
	assert.Equal(t, []string{"id"}, table.Constraints[0].Columns)
}

// EDITIONABLE sits between REPLACE and the object keyword, and the name is
// quoted and schema-qualified. Neither the splitter nor the parser allowed for
// it, so the trigger arrived with no name and no body, and the function was not
// found at all.
func TestOracle_RealDDLRoutines(t *testing.T) {
	schema, err := NewOracle().Parse(realRoutineDDL)
	assert.NoError(t, err)

	assert.Len(t, schema.Triggers, 1)
	trigger := schema.Triggers[0]
	assert.Equal(t, "bump", trigger.Name, "Oracle folds unquoted names, and this parser folds the quoted ones to match")
	assert.Equal(t, "src", trigger.Schema)
	assert.Equal(t, "users", trigger.Table)
	assert.Equal(t, "BEFORE", trigger.Timing)
	assert.Equal(t, "INSERT", trigger.Event)
	assert.True(t, trigger.ForEachRow)
	assert.Contains(t, trigger.Body, "NVL(:NEW.n, 0) + 2")

	assert.Len(t, schema.Functions, 1)
	fn := schema.Functions[0]
	assert.Equal(t, "add_one", fn.Name)
	assert.Equal(t, "NUMBER", fn.Returns)
	assert.Contains(t, fn.Body, "RETURN v + 1")

	assert.Len(t, fn.Parameters, 1)
	assert.Equal(t, "v", fn.Parameters[0].Name)
	assert.Equal(t, "IN", fn.Parameters[0].Direction, "Oracle writes the direction after the name")
	assert.Equal(t, "NUMBER", fn.Parameters[0].DataType)
}

// A PL/SQL block needs IS in front of it, and the parameter direction goes
// after the name.
func TestOracle_RealDDLRoutineRoundTrip(t *testing.T) {
	schema, err := NewOracle().Parse(realRoutineDDL)
	assert.NoError(t, err)

	out, err := NewOracle().Generate(schema)
	assert.NoError(t, err)

	assert.Contains(t, out, "CREATE OR REPLACE FUNCTION add_one(v IN NUMBER) RETURN NUMBER")
	assert.Contains(t, out, "IS\nBEGIN", "a block without IS does not compile")
	assert.Contains(t, out, "CREATE OR REPLACE TRIGGER bump BEFORE INSERT ON users")
	assert.Contains(t, out, "FOR EACH ROW")
	assert.Contains(t, out, ":NEW.n := NVL(:NEW.n, 0) + 2;")
}
